# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: "-G \"Unix Makefiles\" .."
  - script: make alloverse-dist
    workingDirectory: build
    displayName: "Make"
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        build/*.app/**
        build/*.zip
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Alloverse_visor-Mac-x64

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: "-A x64 .."
  - task: VSBuild@1
    displayName: "Visual Studio build"
    inputs:
      msbuildArchitecture: 'x64'
      createLogFile: true
      solution: 'build\PACKAGE.vcxproj'
      configuration: release
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        build/**/*win64.exe
        build/**/*.log
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Alloverse_visor-Windows-x64


- job: Android
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: 'sdkmanager --install "ndk;21.0.6113669"'
    displayName: "Install NDK"
    env:
      PATH: "/Users/runner/Library/Android/sdk/cmake/3.6.4111459/bin:/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
      ANDROID_HOME: "~/Library/Android/sdk"
  - task: DownloadSecureFile@1
    name: debugKeys
    displayName: 'Download debug signing keys'
    inputs:
      secureFile: 'android.debug.keystore'
  - script: |
      echo Moving key into place...
      ln -s $(debugKeys.secureFilePath) $(Build.Repository.LocalPath)/deps/lovr-android/LovrApp/Projects/Android/android.debug.keystore
  - task: DownloadSecureFile@1
    name: releaseKeys
    displayName: 'Download release signing keys'
    inputs:
      secureFile: 'android.release.keystore'
  - script: |
      echo Moving key into place...
      ln -s $(releaseKeys.secureFilePath) $(Build.Repository.LocalPath)/deps/lovr-android/LovrApp/Projects/Android/android.release.keystore
  - task: DownloadSecureFile@1
    name: keyPasswords
    displayName: 'Download signing passwords'
    inputs:
      secureFile: 'keys.properties'
  - script: |
      echo Moving key passwords into place...
      ln -s $(keyPasswords.secureFilePath) $(Build.Repository.LocalPath)/deps/lovr-android/LovrApp/Projects/Android/keys.properties

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: "cmake -DCMAKE_TOOLCHAIN_FILE=~/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a .."
  - script: make alloverse-dist
    workingDirectory: build
    displayName: "Make"
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        build/*.apk
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Alloverse_visor-Android
